Modify pkgs code to provide modified callPackageWith to packages, and modify "pkgs" to include our own ones. Modify pkgs code to include a self-include with architecture forced to i686-linux for 32-bit dependency installation. Adjust dependency package code to try both native and 32bit ld binaries for wrappee loading.

diff --git a/pkgs/pkgs/dep/link_deps b/pkgs/pkgs/dep/link_deps
--- a/pkgs/pkgs/dep/link_deps
+++ b/pkgs/pkgs/dep/link_deps
@@ -24,7 +24,16 @@ RFN=${O}/run.sh
 cat >$RFN <<EOF
 #!${SH}/bin/sh
 export LD_LIBRARY_PATH=${O}/lib/
-exec $(echo ${glibc}/lib/ld-linux*so*) \$@
 
+for ld in ${glibc64}/lib/ld-linux*so* ${glibc32}/lib/ld-linux*so*; {
+  echo -n "Trying \$ld ..."
+  "\$ld" --verify "\$1" >/dev/null || {
+    echo "failed."
+    continue
+  }
+  echo ok.
+  exec \$ld \$@
+}
 EOF
+
 chmod a+x $RFN
